version: "3.8"

volumes:
  postgres_data: {}
  code:

services:

  nginx:
    image: nginx:1.20.2-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      # - .:/code
      - ./compose/nginx/the_eye.conf:/etc/nginx/conf.d/the_eye.conf
    depends_on:
      - web
    networks:
      - vnetwork

  web:
    container_name: the_eye-web
    build:
      context: .
      dockerfile: compose/django/Dockerfile
    command: /bin/sh compose/django/start.sh
    ports:
      - "8000:8000"
    expose:
      - 8000
    depends_on:
      - db
      - redis
    restart: on-failure
    networks:
      - vnetwork

  db:
    container_name: the_eye-db
    image: postgres:13.5-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=the_eye
    restart: on-failure
    networks:
      - vnetwork

  redis:
    image: redis:6.2.6-alpine
    container_name: the_eye-redis
    ports:
      - "6379:6379"
    networks:
      - vnetwork

networks:
  vnetwork:
    driver: bridge